# Generated by Django 5.1.15 on 2026-05-15 06:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                ("intro", models.CharField(blank=True, max_length=300)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("heading", 0), ("paragraph", 1), ("image", 5), ("featured_products", 8)],
                        blank=True,
                        block_lookup={
                            0: ("apps.website.blocks.HeadingBlock", (), {}),
                            1: ("apps.website.blocks.ParagraphBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 160, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("alt_text", 3), ("caption", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Featured products",
                                    "max_length": 120,
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"max_length": 400, "required": False},
                            ),
                            8: ("wagtail.blocks.StructBlock", [[("title", 6), ("intro", 7)]], {}),
                        },
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        help_text="Main heading shown at the top of the homepage.",
                        max_length=120,
                    ),
                ),
                (
                    "hero_tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short supporting line under the hero title.",
                        max_length=240,
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Call-to-action button text. Leave blank to hide the button.",
                        max_length=40,
                    ),
                ),
                (
                    "hero_cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Destination URL for the CTA button (absolute or relative).",
                        max_length=500,
                    ),
                ),
                (
                    "banner",
                    wagtail.fields.StreamField(
                        [("heading", 0), ("paragraph", 1), ("image", 5), ("featured_products", 8)],
                        blank=True,
                        block_lookup={
                            0: ("apps.website.blocks.HeadingBlock", (), {}),
                            1: ("apps.website.blocks.ParagraphBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 160, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("alt_text", 3), ("caption", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Featured products",
                                    "max_length": 120,
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"max_length": 400, "required": False},
                            ),
                            8: ("wagtail.blocks.StructBlock", [[("title", 6), ("intro", 7)]], {}),
                        },
                        help_text="Stackable content sections shown below the hero.",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
