# Generated by Django 5.1.15 on 2026-05-20 08:24

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_product_fulltext_search"),
        ("inventory", "0003_physicalcount_stockadjustment_wastage_and_more"),
        ("master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sale_no", models.CharField(max_length=32, unique=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("POS", "Point of sale"),
                            ("ONLINE", "Storefront / online"),
                            ("B2B", "B2B / wholesale counter"),
                            ("MANUAL", "Manual admin entry"),
                        ],
                        max_length=8,
                    ),
                ),
                ("terminal_id_external", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("HELD", "Held / parked"),
                            ("CONFIRMED", "Confirmed"),
                            ("PARTIALLY_PAID", "Partially paid"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "tax_mode",
                    models.CharField(
                        choices=[("INCLUSIVE", "Tax inclusive"), ("EXCLUSIVE", "Tax exclusive")],
                        default="EXCLUSIVE",
                        max_length=10,
                    ),
                ),
                ("billed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                (
                    "payment_total",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                ("totals_json", models.JSONField(blank=True, default=dict)),
                ("payment_terms_json", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("offline_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="master.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_as_cashier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_as_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sale",
                "verbose_name_plural": "sales",
                "ordering": ("-billed_at", "-id"),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("mrp", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14)),
                ("sale_price", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                ("tax_breakup_json", models.JSONField(blank=True, default=list)),
                (
                    "line_total",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="inventory.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hsn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="master.hsncode",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="master.tax",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="master.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "sale item",
                "verbose_name_plural": "sale items",
                "ordering": ("sale_id", "id"),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PriceOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("original_price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("new_price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("perm_check_passed", models.BooleanField(default=True)),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_price_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_override",
                        to="sales.saleitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "sale price override",
                "verbose_name_plural": "sale price overrides",
                "ordering": ("-id",),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("ref_no", models.CharField(blank=True, max_length=64)),
                ("gateway_txn", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_payments",
                        to="master.paymentmode",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sale payment",
                "verbose_name_plural": "sale payments",
                "ordering": ("sale_id", "at", "id"),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "scope",
                    models.CharField(
                        choices=[("HEADER", "Header (cart-level)"), ("LINE", "Line (per item)")],
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PERCENT", "Percent"), ("FLAT", "Flat amount")], max_length=8
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("condition_json", models.JSONField(blank=True, default=dict)),
                ("requires_approval", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "discount",
                "verbose_name_plural": "discounts",
                "ordering": ("code",),
                "indexes": [
                    models.Index(
                        fields=["is_active", "scope"], name="sales_disco_is_acti_7d9dba_idx"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["branch", "status"], name="sales_sale_branch__2960d8_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["branch", "billed_at"], name="sales_sale_branch__ca3184_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["origin", "status"], name="sales_sale_origin_a94ba3_idx"),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(fields=["sale"], name="sales_salei_sale_id_413ea3_idx"),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(fields=["product"], name="sales_salei_product_f87493_idx"),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(fields=["variant"], name="sales_salei_variant_e0a8ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("product__isnull", False), ("variant__isnull", True)),
                    models.Q(("product__isnull", True), ("variant__isnull", False)),
                    _connector="OR",
                ),
                name="sales_item_xor_target",
            ),
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(fields=["sale", "status"], name="sales_salep_sale_id_40eaa9_idx"),
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(
                fields=["payment_mode", "status"], name="sales_salep_payment_22b2dc_idx"
            ),
        ),
    ]
